version: '3'

services:
  app:
    image: sherif-pro/sh-rif-gpt-ai
    ports:
      - '3000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/dbname

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=yourusername
      - MONGO_INITDB_ROOT_PASSWORD=yourpassword
      - MONGO_INITDB_DATABASE=dbname
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data: